### ISSUE TITLE
qunit updates on deploy and creates changes

### ISSUE THREAD

**Issue by jennschiffer** [bocoup/people#47]
I set up a clone of this app and on `grunt` i noticed changes to qunit files that I didn't make myself (see: https://github.com/bocoup/people/compare/deployment)

should I make a PR to put these changes in, and why did they happen in the first place?

**Comment by tkellen** [comment]
cc @leobalter

**Comment by leobalter** [comment]
my bad.

https://github.com/bocoup/people/blob/deployment/grunt/copy.js#L12

I used the same approach from jQuery UI strategy. The main motivation is something I do not remember (shame on me), but I can ask Timmy from jQuery if they still have an argument to keep it this way.

I see 3 paths we can follow:

1. keep it as it is; QUnit files will have changes on any npm install + grunt copy runs if it gets a minor/patch update.
1. lock QUnit version on package.json, so the commit qunit files will have changes only on a purpose to update it.
1. ignore the copied QUnit files, that will require a `grunt copy` run after any npm install, which we can set up a [post install script](https://github.com/bocoup/people/blob/master/package.json#L6) to minimize any impact. It may even run other grunt tasks.

I believe @jennschiffer will make the best decision out of it as she's the current project champion, right?

**Comment by leobalter** [comment]
I can fix this after you define the best approach.
